---
title: "Information for South African Psychologists 2020: Tariff Code 86205"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(tidyquant)
library(htmltools)
library(plotly)
```

Column {.sidebar data-width=300}
-----------------------------------------------------------------------

### Select Inputs:
```{r}
Gender <- c("Female", "Male")
Age <- seq(14,68,1)
selectInput("gender", "Gender",choices = Gender)
selectInput("age", "Age",choices = Age)
```


### **DISCLAIMER:**
-  The rates displayed apply to the NHRPL (National Health Reference Price List) Tariff Code: 86205 for the year of 2020.

-  All participants in the dataset were diagnosed under ICD10 Code: F43.2.

-  All tariffs are inclusive of VAT.

-  Rates are subject to change by your medical aid and the rates mentioned here are dependent on your level of cover. Please check with your medical aid.

-  The information contained in this document is a guide only. The author cannot be held liable for any inaccuracies in the information.
        
**PLEASE VERIFY WITH YOUR MEDICAL AID.**

### About the data:
-  Total of 1212 observations under diagnosis ICD10: F43.2.
-  Tariff code 86205 is used to designate the rate for Psychology assessment, consultation, counselling and/or therapy (individual or family)for duration: 51-60min.
-  After removing the outliers, total of 1099 observations.
-  Data captured from a single private practice in South Africa.

```{r}
tags$a(href = "https://github.com/SanmariV", "View Source Code Here!")
```

Row {data-height=150, data-width=400}
-----------------------------------------------------------------------

### **Result of selected inputs:**
```{r global, include=FALSE, echo=FALSE}
# Import dataset--------------------------------

data <- read_csv("ICD10_F43.2_patients.csv")
#data %>% glimpse()
data_tib <- as_tibble(data)

#data_tib %>% glimpse()

# Data exploration & Wrangling--------------------------------
# Replace sex variables with more descriptive names
data_tib$gender <- as.character(data_tib$gender)
data_tib$gender[data_tib$gender == "f"] <- "Female"
data_tib$gender[data_tib$gender == "m"] <- "Male"
data_tib$gender <- as.factor(data_tib$gender)

#data_tib %>% glimpse()

data_tib <- data_tib %>% 
    mutate(Birth_year = year(date_of_birth))
    

data_tib <- data_tib %>% 
    mutate(age = round(therapy_year - Birth_year),0) 
    
# How many males in dataset?
males_tib <- data_tib %>% 
    filter(data_tib$gender == "Male") 
   

# How many females in dataset?
females_tib <- data_tib %>% 
    filter(data_tib$gender == "Female")
    

# Remove outliers
# Remove all ages less than 13 and more than 68
# Remove all data where 4 < total-sessions <= 20

data_tib <- data_tib %>% 
    filter(age > 13, age < 68, total_sessions<= 20,total_sessions>4)

# Visualise the dataset
fig1 <- ggplot(data = data_tib, 
               aes(x = age, y = total_sessions, color = gender)) + 
    geom_point(alpha = 0.5) + 
    xlab("Age") +
    ylab("Sessions") +
    theme_tq() +
    #theme(plot.title=element_text(size=7, face="bold", colour="black")) +
    #theme(plot.subtitle=element_text(size=7, face="bold", colour="black")) +
    theme(axis.title.x = element_text(face="bold", colour="black")) +
    theme(axis.title.y = element_text(face="bold", colour="black"))
    
data_tib <- data_tib %>% 
    add_count(age,name="total_people") %>%
    group_by(age) %>% 
    arrange(age) 
    

data_tib <- data_tib %>% 
    mutate(sessions_per_age = tapply(total_sessions, age, FUN=sum))  
    

data_tib_selective <- data_tib %>% 
    select(c("gender","age", "total_people","sessions_per_age"))
   

# Remove duplicates
data_tib_selective <- data_tib_selective[!duplicated(data_tib_selective[,c("gender","age", "total_people","sessions_per_age")]),] 
    

# Calculate average sessions per age
data_tib_selective <- data_tib_selective %>% 
    mutate(avg_sessions = round(sessions_per_age/total_people, 1))  
    

# Rename column names
data_tib_selective <- data_tib_selective %>% 
    rename(average_sessions = avg_sessions)
   

# Info to display in shiny app as a table
display_info <- data_tib_selective %>% 
    select(c("gender", "age","average_sessions"))
    
display_info$age <- as.integer(display_info$age)

# Medical aid rates
medical_aid_rates <- read_csv("medical_aid_rates_2020.csv")
#glimpse(medical_aid_rates)
medical_aid_rates <- as_tibble(medical_aid_rates) %>% 
                    arrange(rate,desc(rate))

fig2 <- ggplot(data=medical_aid_rates, aes(x=medical_aid, y=rate)) +
    geom_bar(stat="identity", fill = "steelblue")+
    geom_text(aes(label=rate), vjust=0.5, hjust=1.3, color="white", size=3.5)+
    labs(
        #title = "**2020 Medical Aid Rates for Psychologists: Tariff Code 86205",
        #subtitle = "Rate for Psychology assessment, consultation, counsellingand/or therapy (individual or family). Duration: 51-60min.",
        x = "Medical Aid Provider",
        y = "Rate (ZAR)"
    ) +
    theme_tq()+
    theme(plot.title=element_text(size=10, face="bold", colour="black")) +
    theme(plot.subtitle=element_text(size=7, face="bold", colour="black")) +
    theme(axis.title.x = element_text(face="bold", colour="black")) +
    theme(axis.title.y = element_text(face="bold", colour="black")) +
    coord_flip()
```


```{r}
    selected <- reactive(display_info %>% 
                        filter(gender == input$gender, age == input$age))

    tableOutput("display_this")
    
    output$display_this <- renderTable(
        selected())
```

### **2020 Medical Aid Rates for Psychologists: Tariff Code 86205**

```{r}
plotOutput("medical_aid_rates", width = 500, height = 500)
           
output$medical_aid_rates <- renderPlot(
           fig2,
        res=96)
```

Row {data-height=350}
-----------------------------------------------------------------------

### **Visualisation of Dataset:** Interactive Plot (Hover with your mouse over the graph)

```{r}
# Input
plotlyOutput("visualise_data_set", width = 500, height = 200)

# Output
output$visualise_data_set <- renderPlotly({
        print(
            ggplotly(fig1))
})
```

