---
title: "python_calcs"
author: "Sanmari Vivier"
date: "6/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(reticulate)
library(tidyverse)
library(lubridate)
library(plotly)
library(tidyquant)

# set conda environment
use_condaenv("py3.8", required = TRUE)

# check if the correct environment is being used
py_config()
```

## R Markdown
```{python}
import pandas as pd
import numpy as np
```


```{python}
# Import the created .csv files
# Females
data_female = pd.read_csv(r'C:/Users/Sanmari Vivier/Dropbox/Personal/r-shiny-app/r-markdown-files/female_dataset_py.csv')
data_female_labels = pd.read_csv(r'C:/Users/Sanmari Vivier/Dropbox/Personal/r-shiny-app/r-markdown-files/female_labels_py.csv')
female_dataset_py = pd.DataFrame(data_female)
female_labels_py = pd.DataFrame(data_female_labels)

# Check to see if it is working
print (female_dataset_py.head(), female_labels_py.head())


# Import the created .csv files----------------------------------
# Males
data_male = pd.read_csv(r'C:/Users/Sanmari Vivier/Dropbox/Personal/r-shiny-app/r-markdown-files/males_dataset_py.csv')
data_male_labels = pd.read_csv(r'C:/Users/Sanmari Vivier/Dropbox/Personal/r-shiny-app/r-markdown-files/males_labels_py.csv')
male_dataset_py = pd.DataFrame(data_male)
male_labels_py = pd.DataFrame(data_male_labels)

# Check to see if it is working
print (male_dataset_py.head(), male_labels_py.head())
```
```{python}
from collections import Counter
import operator

#len(female_dataset_py)
#female_dataset_py.head()

# create age list
#age = np.arange(14,70,1)
#print(type(female_dataset_py))

# convert pd.dataFrame to a list
females = female_dataset_py.values.tolist()
females = np.asarray(females)
#print(females[:10])

# Change shape of array
females = females[:,0]

#print(females[:10])

total_females = Counter()

for age in females:
            if age in total_females:
                total_females[age] += 1
            else:
                total_females[age] = 1

# Convert counter object back to pandas dataframe object
f_according_to_age = pd.DataFrame.from_dict(total_females, orient='index').reset_index()

# Rename columns
f_according_to_age = f_according_to_age.rename(columns={'index':'age', 0:'count'})

#print(f_according_to_age)
#write to a csv file

f_according_to_age.to_csv('C:/Users/Sanmari Vivier/Dropbox/Personal/r-shiny-app/shiny_app/data/f_according_to_age.csv')
```

```{python}
# convert pd.dataFrame to a list
males = male_dataset_py.values.tolist()
males = np.asarray(males)

# Change shape of array
males = males[:,0]

total_males = Counter()

for age in males:
            if age in total_males:
                total_males[age] += 1
            else:
                total_males[age] = 1

# Convert counter object back to pandas dataframe object
m_according_to_age = pd.DataFrame.from_dict(total_males, orient='index').reset_index()

# Rename columns
m_according_to_age = m_according_to_age.rename(columns={'index':'age', 0:'count'})

#print(m_according_to_age)

#write to a csv file
m_according_to_age.to_csv('C:/Users/Sanmari Vivier/Dropbox/Personal/r-shiny-app/shiny_app/data/m_according_to_age.csv')
```

```{r}
install.packages('RColorBrewer')
library(RColorBrewer)
display.brewer.all()

```


```{r}
f_according_to_age <- read_csv('data/f_according_to_age.csv')

head(f_according_to_age)

f_according_to_age <- as_tibble(f_according_to_age) %>% 
                    glimpse()

f_according_to_age <- f_according_to_age %>% 
                    select(age,total) %>%
                    glimpse()

f_according_to_age <- f_according_to_age %>% 
                    arrange(age, total) %>% 
                    glimpse()

fig3 <- ggplot(data = f_according_to_age, 
               aes(x = age, y = total)) +
        geom_bar(stat="identity", fill = '#fc8d62') +
        labs(
            title = "How many females in each age group?",
            subtitle = "") +
        xlab("Age") +
        ylab("Total females in data set") +
        theme_tq()

ggplotly(fig3)
```
```{r}
m_according_to_age <- read_csv('data/m_according_to_age.csv')

head(m_according_to_age)

m_according_to_age <- as_tibble(m_according_to_age) %>% 
                    glimpse()

m_according_to_age <- m_according_to_age %>% 
                    select(age,total) %>%
                    glimpse()

m_according_to_age <- m_according_to_age %>% 
                    arrange(age, total) %>% 
                    glimpse()

fig4 <- ggplot(data = m_according_to_age, 
               aes(x = age, y = total)) +
        geom_bar(stat="identity", fill = '#8da0cb') +
        labs(
            title = "How many males in each age group?",
            subtitle = "") +
        xlab("Age") +
        ylab("Total males in data set") +
        theme_tq()

ggplotly(fig4)
```
```{r}
# What is the average amount of sessions per age group?
# Females

glimpse(females_tib)
glimpse(f_according_to_age)

mean_sessions_per_age_f <- females_tib %>%
                        select(age, gender, total_sessions) %>% 
                        group_by(age) %>% 
                        arrange(age,total_sessions) %>% 
                        summarise(round(mean(total_sessions),3))

colnames(mean_sessions_per_age_f)

mean_sessions_per_age_f <- rename(mean_sessions_per_age_f, 
                                  average = 'round(mean(total_sessions), 3)')

fig5 <- ggplot(data = mean_sessions_per_age_f, 
               aes(x = age, y = average)) +
        geom_bar(stat="identity", fill = '#fc8d62') +
        labs(
            title = "Average sessions for females per age group",
            subtitle = "") +
        xlab("Age") +
        ylab("Average sessions") +
        theme_tq()

ggplotly(fig5)




```

```{r}
# Males

mean_sessions_per_age_m <- males_tib %>%
                        select(age, total_sessions) %>% 
                        group_by(age) %>% 
                        arrange(age,total_sessions) %>% 
                        summarise(round(mean(total_sessions),3))

mean_sessions_per_age_m <- rename(mean_sessions_per_age_m, 
                                  average ='round(mean(total_sessions), 3)')

view(mean_sessions_per_age_m)

fig6 <- ggplot(data = mean_sessions_per_age_m, 
               aes(x = age, y = average)) +
        geom_bar(stat="identity", fill = '#8da0cb') +
        labs(
            title = "Average sessions for males per age group",
            subtitle = "") +
        xlab("Age") +
        ylab("Average sessions") +
        theme_tq()

ggplotly(fig6)
```


